name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-leptos
        run: cargo install cargo-leptos --locked

      - name: Build (server + client assets)
        env:
          LEPTOS_OUTPUT_NAME: my-webpage
          LEPTOS_SITE_ROOT: site
          LEPTOS_SITE_PKG_DIR: pkg
          LEPTOS_ENV: PROD
        run: cargo leptos build --release -vv

      - name: Stage bundle
        run: |
          set -e
          mkdir -p staging dist
          cp target/release/my-webpage staging/
          cp -r site staging/site
          cp example.env staging/.env
          tar -C staging -czf dist/my-webpage-${GITHUB_REF_NAME}-linux-x86_64.tar.gz my-webpage .env site

      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.tar.gz > SHA256SUMS
          sha512sum *.tar.gz > SHA512SUMS

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/my-webpage-${{ github.ref_name }}-linux-x86_64.tar.gz
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
